---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: build
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: build
    schedule:
      interval: weekly
    labels:
      - dependencies
